export enum DealStage {
  CONSULTING = 'CONSULTING',
  CONTRACTING = 'CONTRACTING',
  CONTRACT_CONFIRMED = 'CONTRACT_CONFIRMED',
  MONGOL_ASSIGNING = 'MONGOL_ASSIGNING',
  MONGOL_ASSIGNED = 'MONGOL_ASSIGNED',
  ON_HOLD = 'ON_HOLD',
  BEFORE_DEPARTURE_10D = 'BEFORE_DEPARTURE_10D',
  BEFORE_DEPARTURE_3D = 'BEFORE_DEPARTURE_3D',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
}
