export enum MealOption {
  CAMP_MEAL = 'CAMP_MEAL',
  LOCAL_MEAL = 'LOCAL_MEAL',
  LOCAL_RESTAURANT = 'LOCAL_RESTAURANT',
  PORK_PARTY = 'PORK_PARTY',
  HORHOG = 'HORHOG',
  SHASHLIK = 'SHASHLIK',
  SHABU_SHABU = 'SHABU_SHABU',
}
