export enum VehicleType {
  STAREX = 'STAREX',
  HIACE_SHORT = 'HIACE_SHORT',
  HIACE_LONG = 'HIACE_LONG',
  PURGON = 'PURGON',
  PREMIUM_VAN = 'PREMIUM_VAN',
  SUV = 'SUV',
  LAND_CRUISER = 'LAND_CRUISER',
  ALPHARD = 'ALPHARD',
  OTHER = 'OTHER',
}
