export const dealPipelineTokens = {
  board: {
    section: 'grid gap-4',
    track: 'overflow-x-auto pb-2',
    grid: 'grid min-w-max grid-flow-col auto-cols-[260px] gap-4',
    searchHint: 'text-xs text-slate-500',
    errorText: 'text-sm text-rose-600',
    loadingText: 'text-sm text-slate-600',
  },
  column: {
    base: 'rounded-2xl border border-slate-200 bg-slate-100/70 p-3 transition-colors',
    over: 'bg-slate-200/60',
    header: 'mb-3 flex items-center justify-between gap-2 border-b border-slate-200 pb-2',
    title: 'text-sm font-semibold text-slate-900',
    count: 'rounded-full bg-slate-200 px-2 py-0.5 text-xs font-medium text-slate-700',
    emptyCard: 'rounded-xl border border-dashed border-slate-300 bg-white/70 p-3 text-xs text-slate-500 shadow-none',
  },
  card: {
    wrapperCursor: 'cursor-pointer',
    base: 'rounded-xl border border-slate-200 bg-white p-3 shadow-sm',
    dragging: 'opacity-60',
    title: 'text-sm font-semibold text-slate-900',
    subtitle: 'text-xs text-slate-500',
  },
  drawer: {
    overlay: 'fixed inset-0 z-50',
    backdrop: 'absolute inset-0 bg-black/30',
    panel: 'absolute right-0 top-0 h-full w-full max-w-2xl overflow-y-auto border-l border-slate-200 bg-slate-50 shadow-2xl',
    header: 'border-b border-slate-200 bg-white px-6 py-5',
    headingTopLabel: 'text-xs font-medium text-slate-500',
    headingTitle: 'mt-1 text-xl font-semibold tracking-tight text-slate-900',
    closeButton: 'rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs text-slate-600 hover:bg-slate-100',
    infoCard: 'mt-4 grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700',
    infoRow: 'grid grid-cols-[110px_minmax(0,1fr)] items-center gap-2',
    infoLabel: 'text-slate-500',
    infoEmphasis: 'font-medium text-slate-900',
    tabsWrap: 'border-b border-slate-200 bg-white px-6',
    tabsRow: 'flex items-center gap-6',
    tabButtonBase: 'border-b-2 py-3 text-sm font-medium transition-colors',
    tabButtonActive: 'border-slate-900 text-slate-900',
    tabButtonInactive: 'border-transparent text-slate-500 hover:text-slate-800',
    contentWrap: 'px-6 py-6',
    sectionLabel: 'text-xs font-semibold tracking-wide text-slate-500',
    noteComposerToggle: 'rounded-lg border border-slate-300 bg-white px-2.5 py-1 text-xs text-slate-700 hover:bg-slate-100',
    noteComposerCard: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-none',
    fieldLabel: 'text-xs text-slate-500',
    fieldInput: 'rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-900 outline-none focus:border-slate-900',
    fieldTextarea: 'w-full rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-900 outline-none focus:border-slate-900',
    noteError: 'text-xs text-rose-600',
    noteSubmitButton:
      'rounded-xl bg-slate-900 px-3 py-2 text-xs font-medium text-white hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-400',
    notesLoading: 'text-xs text-slate-500',
    notesEmptyCard: 'rounded-2xl border border-dashed border-slate-300 bg-white p-4 text-sm text-slate-500 shadow-none',
    noteItemCard: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-none',
    noteMetaRow: 'mb-2 flex items-center justify-between gap-2 text-xs',
    noteMetaAuthor: 'text-slate-500',
    noteMetaDateStrong: 'font-semibold text-slate-900',
    noteMetaTime: 'text-slate-500',
    noteText: 'whitespace-pre-wrap text-sm text-slate-900',
    simpleCard: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-none',
    todoLoading: 'text-xs text-slate-500',
    todoError: 'text-xs text-rose-600',
    todoEmptyCard: 'rounded-2xl border border-dashed border-slate-300 bg-white p-4 text-sm text-slate-500 shadow-none',
    todoGroupWrap: 'grid gap-2',
    todoGroupHeader: 'mt-2 flex items-center justify-between border-b border-slate-200 pb-1',
    todoGroupTitle: 'text-sm font-semibold text-slate-900',
    todoGroupCount: 'rounded-full bg-slate-200 px-2 py-0.5 text-[11px] text-slate-700',
    todoItemMetaRow: 'mb-2 flex items-center justify-between gap-2 text-xs text-slate-500',
    todoItemTitle: 'text-sm font-semibold text-slate-900',
    todoItemDescription: 'mt-1 whitespace-pre-wrap text-sm text-slate-700',
    todoStatusButtons: 'mt-3 flex flex-wrap gap-2',
    todoStatusButtonBase:
      'rounded-lg border px-2.5 py-1 text-xs font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-50',
    todoStatusButtonActive: 'border-slate-900 bg-slate-900 text-white',
    todoStatusButtonInactive: 'border-slate-300 bg-white text-slate-700 hover:bg-slate-100',
  },
} as const;
