ALTER TABLE `PlanVersionPricingLine`
  MODIFY COLUMN `lineCode` ENUM(
    'BASE',
    'BASE_PERCENT',
    'BASE_UPLIFT_5PLUS_5PCT',
    'BASE_UPLIFT_5PLUS_10PCT',
    'LONG_DISTANCE',
    'NIGHT_TRAIN',
    'PICKUP_DROP',
    'EXTRA_LODGING',
    'LODGING_SELECTION',
    'CONDITIONAL',
    'HIACE',
    'EARLY',
    'EXTEND',
    'MANUAL_ADJUSTMENT'
  ) NOT NULL;
