ALTER TABLE `SegmentVersion`
  ADD COLUMN `overrideLodgingIsUnspecified` BOOLEAN NULL,
  ADD COLUMN `overrideLodgingName` VARCHAR(191) NULL,
  ADD COLUMN `overrideHasElectricity` ENUM('YES', 'LIMITED', 'NO') NULL,
  ADD COLUMN `overrideHasShower` ENUM('YES', 'LIMITED', 'NO') NULL,
  ADD COLUMN `overrideHasInternet` ENUM('YES', 'LIMITED', 'NO') NULL,
  ADD COLUMN `overrideBreakfast` ENUM('CAMP_MEAL', 'LOCAL_RESTAURANT', 'SHABU_SHABU', 'PORK_PARTY', 'HORHOG', 'SHASHLIK') NULL,
  ADD COLUMN `overrideLunch` ENUM('CAMP_MEAL', 'LOCAL_RESTAURANT', 'SHABU_SHABU', 'PORK_PARTY', 'HORHOG', 'SHASHLIK') NULL,
  ADD COLUMN `overrideDinner` ENUM('CAMP_MEAL', 'LOCAL_RESTAURANT', 'SHABU_SHABU', 'PORK_PARTY', 'HORHOG', 'SHASHLIK') NULL;
