mutation UpdateAppSettings($input: AppSettingsInput!) {
  updateAppSettings(input: $input) {
    movementIntensityColors {
      level
      color
    }
    rentalItemPresets {
      id
      name
      current
      sharedQuantityRules {
        id
        minHeadcount
        maxHeadcount
        quantity
      }
      items {
        id
        label
        unit
        quantityFormula
      }
    }
    tourListRentalItemStock {
      drone
      starlink
      powerbank
    }
    updatedAt
  }
}
