-- AlterEnum (MySQL)
ALTER TABLE `MealSet` MODIFY `breakfast` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL,
    MODIFY `lunch` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL,
    MODIFY `dinner` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL;

-- AlterEnum (MySQL)
ALTER TABLE `SegmentVersion` MODIFY `overrideBreakfast` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL,
    MODIFY `overrideLunch` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL,
    MODIFY `overrideDinner` ENUM('CAMP_MEAL', 'HOTEL_BREAKFAST', 'LOCAL_MEAL', 'LOCAL_RESTAURANT', 'PORK_PARTY', 'PORK_BUFFET', 'HORHOG', 'SHASHLIK', 'SHABU_SHABU') NULL;
